project_name: stampy
version: 2
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
#      - windows
#      - darwin
    goarch:
      - amd64
#      - arm64
nfpms:
-
  maintainer: Jelloeater <jello@jelloeater.me>
  bindir: /usr/local/bin
  description: Copy formatted timestamp to system clipboard
  homepage: https://github.com/Jelloeater/stampy
  license: MIT
  formats:
  - deb
