version: '3'

tasks:
    default:
        dir: .
        cmds:
            - go mod download
            - go mod tidy
            - go mod verify
            - go fmt .
            - go vet .
            - go clean .
            - task: build
        silent: false

    build:
        - rm -rf ./build
        - mkdir ./build
        - go build -o ./build .
        - ./build/stampy

    install-hooks:
        cmds:
#            - pip install pre-commit
#            - pip install --upgrade pre-commit
            - pre-commit install
    remove-hooks:
        ignore_error: true
        cmds:
            - pre-commit uninstall
            - rm .git/hooks -rf
