version: '3'

tasks:
    default:
        cmds:
            - go fmt .
            - go vet .
            - go clean .
            - rm -rf ./build
            - mkdir ./build
            - go build -o ./build .
            - ./build/stampy
        silent: false

    install-hooks:
        cmds:
            - pip install pre-commit
            - pip install --upgrade pre-commit
            - pre-commit install
    remove-hooks:
        ignore_error: true
        cmds:
            - pre-commit uninstall
            - rm .git/hooks -rf
